name: Waka Readme

on:
    schedule:
      # Runs at 12am IST
      - cron: '0 0 * * *'
    workflow_dispatch:
jobs:
    update-readme:
      name: Update Readme with Metrics
      runs-on: ubuntu-latest
      steps:
        - uses: anmol098/waka-readme-stats@master
          with:
            WAKATIME_API_KEY: "62612680-b240-4d7f-8748-9ae2616661e5"
            GH_TOKEN: "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"
            LOCALE: "ko"
            SHOW_LINES_OF_CODE: "True"
            SHOW_PROFILE_VIEWS: "True"
            SHOW_DAYS_OF_WEEK: "True"
            SHOW_SHORT_INFO: "True"
            SHOW_LOC_CHART: "True"
            SHOW_PROJECTS: "True"
            SHOW_LANGUAGE_PER_REPO: "True"
